### ISSUE TITLE
Don't actually build cljs

### ISSUE THREAD

**Issue by martinklepsch** [crisptrutski/boot-cljs-test#11]
Since this can now run `:none` builds there is no need to compile the build as part of the test task, right?

**Comment by crisptrutski** [comment]
End users understanding to create post and pre tasks is a bit advanced - so wrapping up is convenient. Since the namespace and doo dependency are added dynamically, running that compile inside seems convenient.

The prep and run tasks are part of the public API for advanced users, let's just furnish an example.

**Comment by crisptrutski** [comment]
@martinklepsch closing this as I think the default "porcelain" task is the best default, and the lower level tasks are public. feel free to reopen if you'd like to present another approach
