### ISSUE TITLE
Ensure karma is installed

### ISSUE THREAD

**Issue by crisptrutski** [crisptrutski/boot-cljs-test#30]
This is something `doo` can take care of, just need to call the appropriate method at the right time.

Side note - `lein doo` only seems to do this in one of the branches (`auto` vs `once`) - that's probably a small bug to be addressed too

**Comment by Deraen** [comment]
I think the correct error is already thrown by `run-script`: https://github.com/bensu/doo/blob/master/library/src/doo/core.clj#L275

```
❯ boot test-cljs -e chrome -n frontend.core-test -u target      
Writing clj_test/suite.cljs...
Writing output.cljs.edn...
Compiling ClojureScript...
• output.js
Running cljs tests...[doo] Failed to run command:  #error {
...
}
We tried running karma but we couldn't find it your system. Try:

     karma -v 

If it doesn't work you need to install karma, see https://github.com/bensu/doo#setting-up-environments

If it does work, file an issue and we'll sort it together!
```

There are other problems though.

After installing karma-cli, `karma` is succesfully called but it can't find the `node_modules`. I think this is caused by Boot temp-dirs. Probably because doo is called with exec-dir set to directory of created JS file, and thus node_modules should also exist on that directory.

If we wanted, we could automate the whole node package installation, using webjars should remove need for using npm completely. We would probably need to copy the node_modules contents to same directory as the output file: https://github.com/cljsjs/packages/blob/master/highlight/build.boot#L47-L51

**Comment by crisptrutski** [comment]
Webjars solution sounds interesting. Using `doo`s `:paths` option seemed the least invasive though, and we could possibly avoid any copying.

Thinking of providing an option to just leverage the `target` task and forget about running with `exec-dir` even. This would be an escape hatch for any cases like this (say a new `testem` test runner)

**Comment by Deraen** [comment]
I'm against using target task for this. The correct use of target task is only to copy the build artifacts to a place where they can be copied to other places (deployed to server etc.). Long running tasks shouldn't use it to create directories. Instead tasks can just use tmp-dirs and copy files there manually, the same functions can be used as what Boot uses for target task.

Also, the `:paths` only work for binaries, I'm not sure how that works with `node_modules`? Perhaps it works, as I seem to be able to call node scripts from outside the directory and they correctly use `node_modules` relative to the script.

**Comment by crisptrutski** [comment]
Thanks for the guidance on when to use `target`. My feeling was that it's "OK" as shortcut for using "written with lein in mind" tooling, especially to handle "the nth situation you hadn't thought of before", but you're probably right in this case. As `boot` becomes more popular, tooling libraries will just need to consider it :smile:  

Luckily the `doo` team have been super awesome, and even run tests via `boot` in their CI now

**Comment by Deraen** [comment]
Btw, here's the code which can be used to copy files from fileset to any dir: https://github.com/boot-clj/boot/blob/master/boot/core/src/boot/task/built_in.clj#L220-L224

Fileset-syncer takes in collection of paths as strings, but I think it can as well be called with collection of Files (the tmp-dir). By using this one gets all the performance optimizations for free.

**Comment by crisptrutski** [comment]
Nice!

**Comment by crisptrutski** [comment]
Will track this as part of #35
