### ISSUE TITLE
Not possible to set namespaces from CLI

### ISSUE THREAD

**Issue by Deraen** [crisptrutski/boot-cljs-test#32]
Because namespaces option is defined as `#{str}` it is not possible to define symbols of namespaces when invoking `cljs-test` from cli: `boot test-cljs -n frontend.core-test` will fail because namespace is passed in as string.

I think the correct solution here would be to define the type of namespaces argument as `edn` and document and assert that it is a string. It shouldn't change the behavior when task is used from clj but it allows setting namespaces from cli: `boot test-cljs -n "#{frontend.core-test}"`  (no `'` in EDN).

**Comment by crisptrutski** [comment]
I'm not sure I understand how the test will fail - the string parameter will become `"\afrontend.core-test\z"` which should have the same semantics as the symbol?

The reason I took the approach above so that the regex approach had legs to take to `boot-test` if we wanted to standardise, and didn't want to break legacy CLI usage.

If I understand your reason to use `edn` instead of `#{edn}` - this is so non-collections get treated as strings instead of symbols? This would then only work for single namespaces? Must be misunderstanding, as that doesn't seem natural

**Comment by crisptrutski** [comment]
Just sanity checked current implementation in examples dir:

```
boot testing test-cljs -n boot-cljs-test-example.app-test
boot testing test-cljs -n boot-cljs-test-example.\*-test
boot testing test-cljs -n boot-cljs-test-example.\*
boot testing test-cljs -n boot-cljs-test-example.app -n boot-cljs-test-example.app-test
```

They all work just as I'd expect, and seem perfectly general.

Using `edn` loses chainability and makes the CLI usage a bit more finicky without any tangible benefits I can see.

**Comment by Deraen** [comment]
Hmm, maybe I couldn't get current behavior working because current code didn't write cljs.edn so all namespaces where loaded anyway.

**Comment by crisptrutski** [comment]
OK, well I'll leave this open in case you still get issues, or have any other ideas for the API, but prefer what we have currently to the `edn` with custom validation idea.

@micha helped me bikeshed current str/sym/regex overloading so worst case _appeal to authority_ :wink:

**Comment by crisptrutski** [comment]
Just closing to declutter, but welcome to reopen and resume discussion
