### ISSUE TITLE
Work with speak on errors

### ISSUE THREAD

**Issue by jupl** [crisptrutski/boot-cljs-test#46]
Currently when using this task with `speak` the sound always plays success even if tests fail. It would be neat if errors (warnings if there's a use case too?) are supported as well.

**Comment by crisptrutski** [comment]
Great suggestion.

Guessing the beep is coming from successful `boot-cljs` compiles, we should be able to suppress that and trigger our own.

PR welcome 😉

**Comment by crisptrutski** [comment]
Turns out this is as simple as throwing exceptions. For warnings there an atom `boot.core/*warnings*` that can be appended too, I've added that for the "script not found" and "using deprecated args" cases, but leaving it off for this (still text warning for visibility) automatic adding of missing dependencies.

Will push a `0.3.0-SNAPSHOT` build this evening containing this, thanks again for the idea.

**Comment by crisptrutski** [comment]
Oh, and it'll also work with `notify`, the replacement for `speak`
