### ISSUE TITLE
Support new boot-cljs `2.1.2`

### ISSUE THREAD

**Issue by burn2delete** [crisptrutski/boot-cljs-test#65]
This error is happening as of upgrading from boot-cljs `2.0.0`

**Comment by crisptrutski** [comment]
Thanks for reporting - do you have a stacktrace?

**Comment by crisptrutski** [comment]
Looks like something to do with the asset-path changes - are you also getting this: `ClojureScript could not load :main, did you forget to specify :asset-path?`?

**Comment by crisptrutski** [comment]
Dug into a few cases and can confirm the issue is with the changed asset-path convention - eg. with :id `beep/boop` the stub `index.html` is being created inside the `beep` directory, and then looking for `beep/boop.out/goog/base.js`. i.e. the path is being handled twice.

Will likely need to cut a new version with either no prior to `2.1.0` boo-cljs support, or branching on the version found. Should be able to find some time this weekend 🙂

**Comment by burn2delete** [comment]
Yes that is the correct error, I'm not sure why I didn't paste it before.

**Comment by crisptrutski** [comment]
0.3.3-SNAPSHOT published for testing 🌮

**Comment by burn2delete** [comment]
working!

**Comment by crisptrutski** [comment]
Thanks for confirming 😌
